### ISSUE TITLE
Malformed header (B64) received on Shockwave crashes extensions

### ISSUE THREAD

**Issue by b7c** [b7c/Xabbo.GEarth#2]
After sending `REMOVERIGHTS`, the server responds with a malformed header:
```
[REMOVERIGHTS]
Outgoing[97] -> Aab7
--------------------
Incoming[3585] -> xA[0]
--------------------
Incoming[-81] -> öï[0][2]/ì
```

Which causes the following exception:
```
[04:08:27.647] crit: Xabbo.GEarth.GEarthExtension[0] Invalid byte encountered when decoding B64: 0xf6.
System.ArgumentException: Invalid byte encountered when decoding B64: 0xf6.
    at Xabbo.Messages.B64.Decode(ReadOnlySpan`1 buf) in Xabbo.Common/Messages/B64.cs:line 58
    at Xabbo.GEarth.GEarthExtension.ParseInterceptArgs(Packet packet) in Xabbo.GEarth/GEarthExtension.cs:line 541
    at Xabbo.GEarth.GEarthExtension.HandlePacketIntercept(Packet rawPacketIntercept) in Xabbo.GEarth/GEarthExtension.cs:line 559
    at Xabbo.GEarth.GEarthExtension.HandlePacket(Packet packet) in Xabbo.GEarth/GEarthExtension.cs:line 456
    at Xabbo.GEarth.GEarthExtension.ProcessPipeAsync(PipeReader reader, CancellationToken cancellationToken) in Xabbo.GEarth/GEarthExtension.cs:line 383
    at Xabbo.GEarth.GEarthExtension.HandleInterceptorAsync(GEarthConnectOptions connectOpts, CancellationToken cancellationToken) in Xabbo.GEarth/GEarthExtension.cs:line 303
```

Hex dump:
```
[REMOVERIGHTS]
00000000  41 61 62 37        |Aab7|
--------------------
00000000  78 41 00           |xA□|
--------------------
00000000  f6 ef 00 02 2f ec  |□□□□/□|
```

`öï` is encoded as `f6 ef` which is not a valid `B64` (each byte must start with the bits `01`).

**Comment by b7c** [comment]
Ignoring these kinds of packets and reflecting them back to G-Earth for now as the headers cannot be round-tripped to/from B64
